# GITHUB: 1SniFo | MIT License - Copyright (c) 2020 1SniFo
# Feel free to donate BTC >> 1DAsb5VhKhYugKtEH5JSTimijYiCZaVEdH
# Version 2.1
main:
  # we are using threads for large combos and prevent crash from bad pc
  threads: 100
  # Chat colors
  color: true
  # input
  Read:
    # read combo line only is worlds has an specific character
    character: ':'
    # if combo has deferment character can can only one word with specific position
    # line: "test1:123 test2:1264" is position: 2 it will read only test2:1264
    # 0 = last one
    # 1 = first one
    # 2 = second one....
    position: 1
    # reads only with encode type
    # default: ascii
    encode: "ascii"

  # output
  # Remove duplicates from the same lines
  Duplicates: true

  # Reverse the combo
  Reverse: false

  # Write the account(s) if first user characters equal to first password characters and others on the end
  Hot: true

  # Max password length
  # if you want to disable all length enable: false
  # if you want to disable one put 0
  Length:
    enable: true
    # Minimum of password characters
    minimum: 6

  # Edit password
  Edit:
    enable: false
    # random edit password, chance between 0 and 100
    # if you want to disable it put 0
    chance: 50
    # Upper the first character of password
    title: true
    # edit section
    # default: "{password}"
    # example: if password: "!{password}!" and password was 123 it will save it as !123!
    password: "{password}!"
    # if password has specific keywords it will be not edited
    keywords:
      - "!"
  # if the two enabled blacklist & whitelist blacklist it will be disable
  # saves only the whitelist keywords
  Whitelist:
    enable: false
    keywords:
      - "@mail.ru"
      - "@example.com"

  # removes the keyword if found on the line
  Blacklist:
    enable: false
    keywords:
      - "@hotmail.com"
      - "@gmail.com"
      - "@example.com"